"""Add foriegn key to DataTable

Revision ID: 5902a9a0e3c7
Revises: 06d2018d6b60
Create Date: 2025-05-20 17:38:57.284320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '5902a9a0e3c7'
down_revision: Union[str, None] = '06d2018d6b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_table', sa.Column('userId', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False))
    op.create_foreign_key(None, 'data_table', 'user', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_table', type_='foreignkey')
    op.drop_column('data_table', 'userId')
    # ### end Alembic commands ###
