"""Add foriegn key to DataTable_2

Revision ID: da7332ac6bad
Revises: 5902a9a0e3c7
Create Date: 2025-05-20 17:47:26.014413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da7332ac6bad'
down_revision: Union[str, None] = '5902a9a0e3c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('data_table_userId_fkey', 'data_table', type_='foreignkey')
    op.create_foreign_key(None, 'data_table', 'user', ['userId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_table', type_='foreignkey')
    op.create_foreign_key('data_table_userId_fkey', 'data_table', 'user', ['userId'], ['id'])
    # ### end Alembic commands ###
